"""Compare actual official/patched detector functions with injected replies.

Development validation only; this does not simulate the electrical SPI bus.
Requires Python and g++. Supply the driver copy generated by Build-StartupTrace.
"""
import argparse
from pathlib import Path
import subprocess
import tempfile

HERE = Path(__file__).resolve().parents[1]

ARDUINO = r'''
#pragma once
#include <cstdint>
#include <iostream>
#include <iomanip>
struct __FlashStringHelper;
#define F(x) reinterpret_cast<const __FlashStringHelper *>(x)
#define HEX 16
extern uint8_t DDRB,DDRD,PORTB,PORTD,PINB,PIND,SPCR,SPSR;
inline void delay(int) {}
struct SerialMock {
 void print(const __FlashStringHelper *s){std::cout<<reinterpret_cast<const char *>(s);}
 void print(char c){std::cout<<c;}
 void print(uint8_t n){std::cout<<unsigned(n);}
 template<class T> void print(T n){std::cout<<n;}
 void print(uint8_t n,int base){auto flags=std::cout.flags();if(base==16)std::cout<<std::hex<<std::uppercase;std::cout<<unsigned(n);std::cout.flags(flags);}
 template<class T> void println(T n){print(n);std::cout<<"\n";}
 void println(){std::cout<<"\n";}
};
extern SerialMock Serial;
'''

HARNESS = r'''
#include <Arduino.h>
#include <sstream>
#include <cstdlib>
#include "LibraryStartupTrace.h"
uint8_t DDRB=4,DDRD=16,PORTB=4,PORTD=16,PINB=4,PIND=16,SPCR=0x50,SPSR=1;
SerialMock Serial;
int target,failValue;bool resetFail,versionFail;uint8_t lastWrite;
unsigned resetReads;std::ostringstream calls;
class W5100Class {
public:
 static uint8_t chip;
 static uint8_t softReset(),isW5100(),isW5200(),isW5500();
 static void writeMR(uint8_t value){lastWrite=value;resetReads=0;calls<<"W"<<unsigned(value)<<",";}
 static uint8_t readMR(){
   uint8_t value;
   if(chip!=target)value=0xFF;
   else if(lastWrite==0x80)value=(resetFail||resetReads++==0)?0xFF:0;
   else value=(lastWrite==failValue)?0xFF:lastWrite;
   calls<<"R"<<unsigned(value)<<",";return value;
 }
 static uint8_t readVERSIONR_W5200(){calls<<"V52,";return versionFail?0:3;}
 static uint8_t readVERSIONR_W5500(){calls<<"V55,";return versionFail?0:4;}
};
uint8_t W5100Class::chip=0;
// ACTUAL_DETECTORS
int main(int argc,char **argv){
 if(argc!=6)return 2;
 target=std::atoi(argv[1]);failValue=std::atoi(argv[2]);
 resetFail=std::atoi(argv[3]);versionFail=std::atoi(argv[4]);
 libraryStartupTraceSnapshot(LS_BEFORE_SD);
 libraryStartupTraceSnapshot(LS_AFTER_SD);
 libraryStartupTraceSnapshot(LS_BEFORE_ETH);
 uint8_t detected=0;
 if(W5100Class::isW5200())detected=52;
 else if(W5100Class::isW5500())detected=55;
 else if(W5100Class::isW5100())detected=51;
 libraryStartupTraceSnapshot(LS_AFTER_ETH);
 std::cout<<"OUTCOME="<<unsigned(detected)<<"\nCALLS="<<calls.str()<<"\n";
 if(std::atoi(argv[5]))libraryStartupTracePrint();
}
'''


def detectors(path):
    text = Path(path).read_text(encoding="utf-8-sig")
    start = text.index("uint8_t W5100Class::softReset(void)")
    end = text.index("W5100Linkstatus W5100Class::getLinkStatus()", start)
    return text[start:end]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--official-driver", required=True)
    parser.add_argument("--overlay-driver", required=True)
    args = parser.parse_args()
    cases = [
        ("W5100 success", 51, -1, 0, 0, 51, "candidate=W5100 stage=MR00 expected=00 observed=00"),
        ("W5100 reset timeout", 51, -1, 1, 0, 0, "candidate=W5100 stage=RESET expected=00 observed=FF reset_polls=20"),
        ("W5100 MR10 mismatch", 51, 16, 0, 0, 0, "candidate=W5100 stage=MR10 expected=10 observed=FF"),
        ("W5100 MR12 mismatch", 51, 18, 0, 0, 0, "candidate=W5100 stage=MR12 expected=12 observed=FF"),
        ("W5100 MR00 mismatch", 51, 0, 0, 0, 0, "candidate=W5100 stage=MR00 expected=00 observed=FF"),
        ("W5200 success", 52, -1, 0, 0, 52, "candidate=W5200 stage=VERSION expected=03 observed=03"),
        ("W5500 success", 55, -1, 0, 0, 55, "candidate=W5500 stage=VERSION expected=04 observed=04"),
        ("W5200 version mismatch", 52, -1, 0, 1, 0, "candidate=W5200 stage=VERSION expected=03 observed=00"),
    ]
    with tempfile.TemporaryDirectory(prefix="startup-detector-model-") as temp:
        root = Path(temp)
        (root / "Arduino.h").write_text(ARDUINO)
        (root / "LibraryStartupTrace.h").write_text((HERE / "trace/LibraryStartupTrace.h").read_text())
        executables = []
        for name, driver in [("official", args.official_driver), ("trace", args.overlay_driver)]:
            source = root / (name + ".cpp")
            source.write_text(HARNESS.replace("// ACTUAL_DETECTORS", detectors(driver)))
            binary = root / name
            subprocess.run(["g++", "-std=c++11", "-Wall", "-Wextra", "-D__AVR_ATmega328P__",
                            "-I", str(root), str(source), str(HERE / "trace/LibraryStartupTrace.cpp"),
                            "-o", str(binary)], check=True)
            executables.append(binary)
        for label, target, fail, reset, version, expected, trace in cases:
            outputs = []
            for binary in executables:
                outputs.append(subprocess.check_output([str(binary), str(target), str(fail),
                                                       str(reset), str(version), "1"], text=True))
            assert outputs[0].splitlines()[:2] == outputs[1].splitlines()[:2], label + ": changed outcome/call sequence"
            assert outputs[1].startswith("OUTCOME=" + str(expected) + "\n"), label
            assert trace in outputs[1], label + ": wrong trace"
            assert "snapshots=4 overflow=0 buffer_bytes=61" in outputs[1], label
            assert "phase=AFTER_SD eth_out=1 sd_out=1 eth_latch=1 sd_latch=1 eth_pin=1 sd_pin=1 spcr=50 spsr=01" in outputs[1], label
        print(f"DETECTOR TRACE MODEL PASS: {len(cases)} injected reply cases; original outcomes/register-call order preserved; no hardware claim")


if __name__ == "__main__":
    main()
